### PR TITLE
Run `cargo fmt`

### PR DESCRIPTION
**Pull request by ErichDonGubler**
This change is [Reviewable](https://reviewable.io/reviews/panicbit/custom_debug_derive/4)

### CODE REVIEW

**Comment by panicbit** [comment]
Thanks :+1:

**Comment by panicbit** [comment]
I'll probably do a little bit of refactoring and a release tomorrow.

**Comment by ErichDonGubler** [comment]
Sounds good!

**Comment by panicbit** [comment]
I released 0.1.5 on crates.io

**Pull request merged**
